In [2]:
!pip install transformers

     |████████████████████████████████| 3.8 MB 4.9 MB/s 
     |████████████████████████████████| 895 kB 18.5 MB/s 
     |████████████████████████████████| 596 kB 36.8 MB/s 
     |████████████████████████████████| 67 kB 3.3 MB/s 
     |████████████████████████████████| 6.5 MB 20.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


```
from transformers import TFAutoModel, AutoTokenizer
model = TFAutoModel.from_pretrained("<model_name>")
tokenizer = AutoTokenizer.from_pretrained("<model_name>")
```

# Tokenizer실습

In [3]:
from transformers import AutoModel, AutoTokenizer, BertTokenizer

In [4]:
model_name = "bert-base-multilingual-cased"

model = AutoModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/681M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/972k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.87M [00:00<?, ?B/s]

In [5]:
print(tokenizer.vocab_size)

119547


In [6]:
for i, key in enumerate(tokenizer.get_vocab()):
    print(key)
    if i>20:
        break

##viation
Alfons
таким
##mble
##گان
##жується
ymhellach
##иера
apparaît
##шено
Олександра
##тока
##unia
##格
lomanef
##alus
Renania
##וכב
##鎧
##ânia
तेलुगु
serving


In [7]:
text = "이순신은 조선 중기의 무신이다."

In [8]:
print(type(tokenizer))

<class 'transformers.models.bert.tokenization_bert_fast.BertTokenizerFast'>


In [9]:
tokenized_input_text = tokenizer(text, return_tensors="pt")
for key, value in tokenized_input_text.items():
    print("{} : \n\t{}".format(key, value))

input_ids : 
	tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])
token_type_ids : 
	tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
attention_mask : 
	tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [11]:
print(tokenized_input_text['input_ids']) # input text를 tokenizing한 후 vocab의 id
print(tokenized_input_text.input_ids)

tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])
tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])


In [12]:
print(tokenized_input_text['token_type_ids']) # segment id (sentA or sentB)
print(tokenized_input_text.token_type_ids) 

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])


In [14]:
print(tokenized_input_text['attention_mask']) # special token (pad, cls, sep) or not
print(tokenized_input_text.attention_mask)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [15]:
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)

['이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.']


In [17]:
input_ids = tokenizer.encode(text, add_special_tokens=False)
print(input_ids)

[9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119]


In [20]:
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

이순신은 조선 중기의 무신이다.


option

In [23]:
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
    max_length = 5,
    truncation = True
)
print(tokenized_text)

['이', '##순', '##신', '##은', '조선']


In [24]:
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
    max_length = 5,
    truncation = True
)
print(input_ids)

[9638, 119064, 25387, 10892, 59906]


In [25]:
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

이순신은 조선


In [26]:
print(tokenizer.pad_token)
print(tokenizer.pad_token_id)

[PAD]
0


In [27]:
tokenized_text = tokenizer.tokenize(
    text,
    add_special_tokens = False,
    max_length = 20,
    padding = "max_length"
)
print(tokenized_text)

['이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']


In [29]:
input_ids = tokenizer.encode(
    text,
    add_special_tokens = False,
    max_length = 20,
    padding = "max_length"
)
print(input_ids)

[9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [30]:
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

이순신은 조선 중기의 무신이다. [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]


## 새로운 토큰을 추가해보자!

In [31]:
text = "깟빼뜨랑 리뿔이 뜨럽거 므리커럭이 케쇼쇼쇽 나오애쇼쇼쇼 우뤼갸갸갸 청쇼랴료다혀뚜요"

tokenized_text = tokenizer.tokenize(text, add_special_tokens=False)
print(tokenized_text)
input_ids = tokenizer.encode(text, add_special_tokens=False)
print(input_ids)
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

['[UNK]', '리', '##뿔', '##이', '뜨', '##럽', '##거', '므', '##리', '##커', '##럭', '##이', '[UNK]', '나', '##오', '##애', '##쇼', '##쇼', '##쇼', '[UNK]', '청', '##쇼', '##랴', '##료', '##다', '##혀', '##뚜', '##요']
[100, 9238, 119021, 10739, 9151, 118867, 41521, 9308, 12692, 106826, 118864, 10739, 100, 8982, 28188, 119121, 119060, 119060, 119060, 100, 9751, 119060, 118862, 38688, 11903, 80579, 118841, 48549]
[UNK] 리뿔이 뜨럽거 므리커럭이 [UNK] 나오애쇼쇼쇼 [UNK] 청쇼랴료다혀뚜요


In [32]:
added_token_num = tokenizer.add_tokens(["깟빼뜨랑","케쇼쇼쇽","우뤼갸갸갸"])
print(added_token_num)

3


In [33]:
tokenized_text = tokenizer.tokenize(text, add_special_tokens=False)
print(tokenized_text)
input_ids = tokenizer.encode(text, add_special_tokens=False)
print(input_ids)
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

['깟빼뜨랑', '리', '##뿔', '##이', '뜨', '##럽', '##거', '므', '##리', '##커', '##럭', '##이', '케쇼쇼쇽', '나', '##오', '##애', '##쇼', '##쇼', '##쇼', '우뤼갸갸갸', '청', '##쇼', '##랴', '##료', '##다', '##혀', '##뚜', '##요']
[119547, 9238, 119021, 10739, 9151, 118867, 41521, 9308, 12692, 106826, 118864, 10739, 119548, 8982, 28188, 119121, 119060, 119060, 119060, 119549, 9751, 119060, 118862, 38688, 11903, 80579, 118841, 48549]
깟빼뜨랑 리뿔이 뜨럽거 므리커럭이 케쇼쇼쇽 나오애쇼쇼쇼 우뤼갸갸갸 청쇼랴료다혀뚜요


In [34]:
text = "[hyerim]이순신은 조선 중기의 무신이다.[/hyerim]"

tokenized_text = tokenizer.tokenize(text, add_special_tokens=False)
print(tokenized_text)
input_ids = tokenizer.encode(text, add_special_tokens=False)
print(input_ids)
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

['[', 'hy', '##eri', '##m', ']', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[', '/', 'hy', '##eri', '##m', ']']
[164, 15165, 13227, 10147, 166, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 164, 120, 15165, 13227, 10147, 166]
[ hyerim ] 이순신은 조선 중기의 무신이다. [ / hyerim ]


In [35]:
text = "[hyerim]이순신은 조선 중기의 무신이다.[/hyerim]"

added_token_num += tokenizer.add_special_tokens({"additional_special_tokens" : ["[hyerim]", "[/hyerim]"]})

tokenized_text = tokenizer.tokenize(text, add_special_tokens=False)
print(tokenized_text)
input_ids = tokenizer.encode(text, add_special_tokens=False)
print(input_ids)
decoded_ids = tokenizer.decode(input_ids)
print(decoded_ids)

['[hyerim]', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[/hyerim]']
[119550, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 119551]
[hyerim] 이순신은 조선 중기의 무신이다. [/hyerim]


In [36]:
# single input
single_seg_input = tokenizer("이순신은 조선 중기의 무신이다.")

# Multiple input
multi_seg_input = tokenizer("이순신은 조선 중기의 무신이다.", "그는 임진왜란을 승리로 이끌었다.")

print("Single segment token(str) : {}".format(tokenizer.convert_ids_to_tokens(single_seg_input['input_ids'])))
print("Single segment token(int) : {}".format(single_seg_input['input_ids']))
print("Single segment type : {}".format(single_seg_input['token_type_ids']))

# Segments
print()
print("Single segment token(str) : {}".format(tokenizer.convert_ids_to_tokens(multi_seg_input['input_ids'])))
print("Single segment token(int) : {}".format(multi_seg_input['input_ids']))
print("Single segment type : {}".format(multi_seg_input['token_type_ids']))

Single segment token(str) : ['[CLS]', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[SEP]']
Single segment token(int) : [101, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 102]
Single segment type : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Single segment token(str) : ['[CLS]', '이', '##순', '##신', '##은', '조선', '중', '##기의', '무', '##신', '##이다', '.', '[SEP]', '그는', '임', '##진', '##왜', '##란', '##을', '승', '##리로', '이', '##끌', '##었다', '.', '[SEP]']
Single segment token(int) : [101, 9638, 119064, 25387, 10892, 59906, 9694, 46874, 9294, 25387, 11925, 119, 102, 17889, 9644, 18623, 119164, 49919, 10622, 9484, 100434, 9638, 118705, 17706, 119, 102]
Single segment type : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


## Bert 모델 테스트

In [37]:
text = "이순신은 [MASK] 중기의 무신이다."
tokenized_text = tokenizer.tokenize(text)
print(tokenized_text)

['이', '##순', '##신', '##은', '[MASK]', '중', '##기의', '무', '##신', '##이다', '.']


In [38]:
from transformers import pipeline

nlp_fill = pipeline('fill-mask', model=model_name)
nlp_fill("이순신은 [MASK] 중기의 무신이다.")

Some weights of the model checkpoint at bert-base-multilingual-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


[{'score': 0.8747122883796692,
  'sequence': '이순신은 조선 중기의 무신이다.',
  'token': 59906,
  'token_str': '조선'},
 {'score': 0.0643644779920578,
  'sequence': '이순신은 청 중기의 무신이다.',
  'token': 9751,
  'token_str': '청'},
 {'score': 0.010954882018268108,
  'sequence': '이순신은 전 중기의 무신이다.',
  'token': 9665,
  'token_str': '전'},
 {'score': 0.004647170193493366,
  'sequence': '이순신은종 중기의 무신이다.',
  'token': 22200,
  'token_str': '##종'},
 {'score': 0.0036106768529862165,
  'sequence': '이순신은기 중기의 무신이다.',
  'token': 12310,
  'token_str': '##기'}]

In [40]:
tokens_pt = tokenizer("이순신은 조선 중기의 무신이다.", return_tensors="pt")
for key, value in tokens_pt.items():
    print("{} : \n\t{}".format(key, value))

outputs = model(**tokens_pt)
last_hidden_state = outputs.last_hidden_state
pooler_output = outputs.pooler_output

print("\nToken wise output : {}, Pooled output : {}".format(last_hidden_state.shape, pooler_output.shape))

input_ids : 
	tensor([[   101,   9638, 119064,  25387,  10892,  59906,   9694,  46874,   9294,
          25387,  11925,    119,    102]])
token_type_ids : 
	tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
attention_mask : 
	tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Token wise output : torch.Size([1, 13, 768]), Pooled output : torch.Size([1, 768])


In [41]:
print(pooler_output)

tensor([[ 2.3151e-01, -8.0099e-02, -1.4249e-01, -1.6500e-01,  4.0655e-02,
         -1.0855e-01, -8.1335e-02,  1.8238e-01, -2.5709e-01,  1.7708e-01,
          5.5793e-02,  2.1646e-01, -2.6028e-01, -1.1805e-01,  1.6879e-01,
          2.2665e-01,  1.6693e-01, -1.4605e-01, -3.3806e-01, -2.5438e-04,
         -9.9437e-01, -3.0201e-01,  7.8168e-02, -2.0071e-01, -2.2053e-02,
          1.8374e-01,  7.8908e-02,  2.7492e-01,  1.5742e-01, -1.8704e-03,
         -1.9677e-01, -9.9644e-01,  5.8323e-01,  2.5800e-01,  1.8723e-01,
         -2.3858e-01,  5.7414e-02,  2.9294e-01,  2.0999e-01, -3.3407e-01,
          9.6668e-02, -1.3142e-01,  1.4946e-01, -2.3270e-01, -1.2149e-01,
         -2.6757e-01, -5.3483e-03,  3.1485e-01, -3.2587e-01, -8.8365e-02,
          2.4172e-01,  1.7982e-01,  3.3085e-01, -2.0571e-01, -2.7982e-02,
          2.8920e-01, -1.2191e-01, -3.7320e-01,  4.6051e-02, -2.3296e-01,
         -2.3272e-01, -4.9195e-02,  9.7081e-02, -8.8512e-02, -5.6786e-02,
         -2.2798e-01,  2.4579e-02, -1.